# =====================================
#  Build angular application
# =====================================
FROM node:16-alpine as angular-built
WORKDIR /usr/src/app
RUN npm install -g @angular/cli
COPY package.json package.json
RUN npm install --silent --force
COPY . .
RUN npm run build

# =====================================
#  hosting front end
# =====================================
FROM nginx:alpine
LABEL author="Cloudtecnologias"
COPY --from=angular-built /usr/src/app/dist/cloudpromo-admin /usr/share/nginx/html
EXPOSE 80
CMD [ "nginx", "-g", "daemon off;" ]