FROM node:20-alpine AS build
WORKDIR /usr/src/app
RUN npm install -g pnpm@10.25.0
COPY .npmrc .
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --ignore-scripts
COPY . .
RUN pnpm run build

FROM nginx:alpine
LABEL author="Cloudtecnologias"
COPY --from=build /usr/src/app/dist/app /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
